name: Build and Deploy Web Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Python dependencies
      run: |
        python3.12 -m venv env
        source env/bin/activate
        pip install -r requirements.txt
        pip install -e .

    - name: Install Node.js dependencies
      run: npm ci

    - name: Build React App
      run: npx webpack

    - name: Deploy Flask App
      run: |
        flask --app collage --debug run --host 0.0.0.0 --port 8001
      env:
        FLASK_APP: collage
        FLASK_ENV: production
        FLASK_RUN_PORT: 8001
        FLASK_RUN_HOST: 0.0.0.0
        PYTHONUNBUFFERED: 1

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build